name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload a Build Artifact # Name of the step
        uses: actions/upload-artifact@v4 # Action to use
        with: # Parameters for the action
          name: my-artifact # Name of the artifact to upload. Optional. Default is 'artifact
          path: .
